language: node_js

node_js:
  - "12"

services:
  - mysql

addons:
  mariadb: '10.4'

git:
  depth: 10

before_install:
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS task_monitoring;'

install:
  - npm install
  - npx sequelize-cli db:migrate
  - npx sequelize-cli db:seed

after_script:
  - bash <(curl -s https://codecov.io/bash)